name: checks

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "*"

permissions:
  actions: write

jobs:
  checks:
    name: checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: "pip"
      - name: cache models and datasets
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/huggingface
          key: ${{ runner.os }}-huggingface-cache-v1  # increment this key to invalidate the cache when new models/datasets are added
      - name: dependencies
        run: |
          python -m pip install --upgrade pip
          # mamba workarounds
          pip install wheel  # see https://github.com/state-spaces/mamba/issues/98
          pip install packaging
          pip install torch==2.1.2
          # end mamba workarounds
          pip install -r requirements.txt
          pip install -e .
      - name: black
        run: black --check .
      - name: isort
        run: isort --check .
      - name: pytest
        run: pytest
