name: checks

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

permissions:
  actions: write

jobs:
  checks:
    name: checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -e .
      - name: black
        run: black --check .
      - name: isort
        run: isort --check .
      - name: pytest
        run: pytest